query getFooterData {
	getFooterNavigation {
		sections {
			section_key,
			headline_mlo_key,
			description_mlo_key,
			elements {
				icon,
				name_mlo_key,
				description_mlo_key,
				show_as_highlight
			}
		}
	}
}