extend type Query {
	getHeaderNavigation: Header!
	getFooterNavigation: Footer!
	getNavigationSection(id: ID!): NavigationSection
}

type Header {
	sections: [NavigationSection!]!
}

type Footer {
	sections: [NavigationSection!]!
}

type NavigationSection {
	section_key: String!
	headline_mlo_key: MLOKey
	description_mlo_key: MLOKey
	elements: [NavigationSectionElement!]!
}

type NavigationSectionElement {
	icon: FontAwesomeIcon
	show_as_highlight: Boolean
	name_mlo_key: MLOKey
	description_mlo_key: MLOKey
}