extend type Query {
	getDocument(identifier: String): Document
}

type Document {
	title: String!
	teaser_image: Image
	markdown_content: String!
}

fragment DocumentProperties on Document {
	title
	teaser_image {
		...ImageProperties
	}
	markdown_content
}